#!/bin/bash

MOUNT_ROOT=$1
MOUNT_SOURCES=${MOUNT_ROOT}/lcnix-sources
MOUNT_PREFIX=${MOUNT_ROOT}/lcnix-stage1
STAGE2_ARGS=-D_LCNIX_BOOTSTRAP_STAGE2=ON -DLCNIX_BUILD_LIBC=ON -DLCNIX_BUILD_SYSTEMD=ON -DCMAKE_INSTALL_PREFIX=/usr \
 -DCMAKE_C_FLAGS="-isystem;/lcnix-stage1/include" \
 -DCMAKE_CXX_FLAGS="-isystem;/lcnix-stage1/include" -DLINK_FLAGS="-L/lcnix-stage1/lib"\
 -DCMAKE_BUILD_TYPE="Release"

scripts/as-root.sh mount -B . $MOUNT_SOURCES

build_stage1(){
    mkdir stage1
    cmake -DCMAKE_INSTALL_PREFIX=${MOUNT_SOURCES} -DLCNIX_BOOTSTRAP_BUILD=ON ..
    cmake --build . --target all -- -j${BOOTSTRAP_JOBS}
    scripts/as-root.sh cmake --build . --target install
}

build_stage2(){
    scripts/as-root.sh scripts/mount-fs.sh
    scripts/as-root.sh chroot /lcnix-stage1/bin/env PATH=/usr/bin:/bin:/usr/sbin:/sbin:/lcnix-stage1/bin:/lcnix-stage1/sbin TERM=$TERM LD_LIBRARY_PATH=/lcnix-stage1/lib \
     /lcnix-stage1/bin/sh /lcnix-sources/scripts/stage2.sh
}


