set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_SYSROOT ${_LCNIX_STAGE_SYSROOT})

set(CMAKE_C_COMPILER_TARGET "${CMAKE_SYSTEM_NAME}-pc-linux-lc")
set(CMAKE_CXX_COMPILER_TARGET "${CMAKE_SYSTEM_NAME}-pc-linux-lc")
set(CMAKE_ASM_COMPILER_TARGET "${CMAKE_SYSTEM_NAME}-pc-linux-lc")