name: C/C++ CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_clang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.0
        with:
          submodules: recursive
      - name: Install Nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
      - name: Clang Build
        uses: ashutoshvarma/action-cmake-build@v1
        with:
          # C Compiler for toolchain
          cc: clang # optional
          # C++ Compiler for toolchain
          cxx: clang++ # optional
          parallel: 8
          build-dir: ${{runner.workspace}}/build-clang
          run-test: true
  build_gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.0
        with:
          submodules: recursive
      - name: Install Nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
      - name: GCC Build
        uses: ashutoshvarma/action-cmake-build@v1
        with:
          # C Compiler for toolchain
          cc: gcc # optional
          # C++ Compiler for toolchain
          cxx: g++ # optional
          parallel: 8
          build-dir: ${{runner.workspace}}/build-gcc
          run-test: true